#!/bin/bash

# pacman error handling
# GNU Affero General Public License v3.0

main() {
  clear;
  echo -e "\n\n\n";

  echo "  1. timeout"
  echo "  2. key-ring"
  echo "  3. mirror"
  echo -e "  4. firmware\n"

  read -p "  error type: " error_type;

  echo -e "\n";
  if [[ $error_type = 1 ]]
  then
    sudo pacman -Syu --disable-download-timeout;
  elif [[ $error_type = 2 ]]
  then
    sudo pacman-key --refresh-keys;
    sudo rm -rf /etc/pacman.d/gnupg;
    sudo pacman-key --init;
    sudo pacman-key --populate archlinux;
  elif [[ $error_type = 3 ]] 
  then
    reflector > ./mirrorlist;
    sudo rm -rf /etc/pacman.d/mirrorlist;
    sudo mv ./mirrorlist /etc/pacman.d/mirrorlist;
  elif [[ $error_type = 4 ]]
  then
    sudo pacman -Rdd linux-firmware;
    sudo pacman -Syu linux-firmware;
  else
    echo "selection \'$error_type\' unavailable";
  fi
}

main
